server:
  port: 8087
  context-path: /service-standard
spring:
  application:
    name: service-standard
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017

eureka:
  instance:
    prefer-id-address: false #是否使用ip注册
    lease-expiration-duration-in-seconds: 30 #续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    fetch-registry: false
    registror-eureka: false
    serviceUrl:
        defaultZone: http://localhost:8088/eureka/